### ISSUE TITLE
Automate build before release/commit?

### ISSUE THREAD

**Issue by fuhrmanator** [NicolasAnquetil/VerveineJ#5]
Today I cloned VerveineJ from moosetechnology and I chased a bug in the verveinej.sh script which turned out to be that there were missing .jar files in lib/ -- in summary, I would like to suggest automating the process so the build is done before releases.

**Comment by NicolasAnquetil** [comment]
Added a pre-push git hook to check that the jar file is newer than any java file
This should do the trick
